/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspaceRouteImport } from './routes/app.workspace'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppApiKeysRouteImport } from './routes/app.api-keys'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks/razorpay'
import { Route as ApiPublicWebhooksN8nRouteImport } from './routes/api/public/webhooks/n8n'
import { Route as ApiPublicV1RemoveBgRouteImport } from './routes/api/public/v1/remove-bg'
import { Route as ApiPublicHooksCleanupExpiredRouteImport } from './routes/api/public/hooks/cleanup-expired'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksN8nRoute = ApiPublicWebhooksN8nRouteImport.update({
  id: '/api/public/webhooks/n8n',
  path: '/api/public/webhooks/n8n',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1RemoveBgRoute = ApiPublicV1RemoveBgRouteImport.update({
  id: '/api/public/v1/remove-bg',
  path: '/api/public/v1/remove-bg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCleanupExpiredRoute =
  ApiPublicHooksCleanupExpiredRouteImport.update({
    id: '/api/public/hooks/cleanup-expired',
    path: '/api/public/hooks/cleanup-expired',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/admin': typeof AppAdminRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/billing': typeof AppBillingRoute
  '/app/history': typeof AppHistoryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/api/public/hooks/cleanup-expired': typeof ApiPublicHooksCleanupExpiredRoute
  '/api/public/v1/remove-bg': typeof ApiPublicV1RemoveBgRoute
  '/api/public/webhooks/n8n': typeof ApiPublicWebhooksN8nRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/admin': typeof AppAdminRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/billing': typeof AppBillingRoute
  '/app/history': typeof AppHistoryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/api/public/hooks/cleanup-expired': typeof ApiPublicHooksCleanupExpiredRoute
  '/api/public/v1/remove-bg': typeof ApiPublicV1RemoveBgRoute
  '/api/public/webhooks/n8n': typeof ApiPublicWebhooksN8nRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/admin': typeof AppAdminRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/billing': typeof AppBillingRoute
  '/app/history': typeof AppHistoryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/api/public/hooks/cleanup-expired': typeof ApiPublicHooksCleanupExpiredRoute
  '/api/public/v1/remove-bg': typeof ApiPublicV1RemoveBgRoute
  '/api/public/webhooks/n8n': typeof ApiPublicWebhooksN8nRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-docs'
    | '/app'
    | '/blog'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/app/admin'
    | '/app/api-keys'
    | '/app/billing'
    | '/app/history'
    | '/app/settings'
    | '/app/workspace'
    | '/api/public/hooks/cleanup-expired'
    | '/api/public/v1/remove-bg'
    | '/api/public/webhooks/n8n'
    | '/api/public/webhooks/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/app'
    | '/blog'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/app/admin'
    | '/app/api-keys'
    | '/app/billing'
    | '/app/history'
    | '/app/settings'
    | '/app/workspace'
    | '/api/public/hooks/cleanup-expired'
    | '/api/public/v1/remove-bg'
    | '/api/public/webhooks/n8n'
    | '/api/public/webhooks/razorpay'
  id:
    | '__root__'
    | '/'
    | '/api-docs'
    | '/app'
    | '/blog'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/app/admin'
    | '/app/api-keys'
    | '/app/billing'
    | '/app/history'
    | '/app/settings'
    | '/app/workspace'
    | '/api/public/hooks/cleanup-expired'
    | '/api/public/v1/remove-bg'
    | '/api/public/webhooks/n8n'
    | '/api/public/webhooks/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRoute
  AppRoute: typeof AppRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksCleanupExpiredRoute: typeof ApiPublicHooksCleanupExpiredRoute
  ApiPublicV1RemoveBgRoute: typeof ApiPublicV1RemoveBgRoute
  ApiPublicWebhooksN8nRoute: typeof ApiPublicWebhooksN8nRoute
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspace': {
      id: '/app/workspace'
      path: '/workspace'
      fullPath: '/app/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/api-keys': {
      id: '/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/n8n': {
      id: '/api/public/webhooks/n8n'
      path: '/api/public/webhooks/n8n'
      fullPath: '/api/public/webhooks/n8n'
      preLoaderRoute: typeof ApiPublicWebhooksN8nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/remove-bg': {
      id: '/api/public/v1/remove-bg'
      path: '/api/public/v1/remove-bg'
      fullPath: '/api/public/v1/remove-bg'
      preLoaderRoute: typeof ApiPublicV1RemoveBgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-expired': {
      id: '/api/public/hooks/cleanup-expired'
      path: '/api/public/hooks/cleanup-expired'
      fullPath: '/api/public/hooks/cleanup-expired'
      preLoaderRoute: typeof ApiPublicHooksCleanupExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppBillingRoute: typeof AppBillingRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppApiKeysRoute: AppApiKeysRoute,
  AppBillingRoute: AppBillingRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRoute,
  AppRoute: AppRouteWithChildren,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksCleanupExpiredRoute: ApiPublicHooksCleanupExpiredRoute,
  ApiPublicV1RemoveBgRoute: ApiPublicV1RemoveBgRoute,
  ApiPublicWebhooksN8nRoute: ApiPublicWebhooksN8nRoute,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
